name: easychat
description: This package helps you to create a chat app easily.
version: 0.0.3
homepage: https://github.com/thruthesky/easychat

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.8.2
  firebase_core: ^2.14.0
  firebase_ui_firestore: ^1.5.4
  firebase_auth: ^4.6.3
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  file_picker: ^5.3.2
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
